### ISSUE TITLE
even without removing container on stop, the system doesn't seem to remember changes?

### ISSUE THREAD

**Issue by kundeng** [dmuth/splunk-lab#13]
I am using orbstack to provide a nice secure ssl, but to do so, I have to disable splunk's own ssl.  

The change seems to work fine, but once I decided to stop the container and restart it,  the change went away.  

How?

**Comment by kundeng** [comment]
YOu seem to have some *.conf.in files in system/local.  Do they somehow magically override existing *.conf?

**Comment by dmuth** [comment]
> The change seems to work fine, but once I decided to stop the container and restart it, the change went away.

You'll need to ask the Orbstack team.

> YOu seem to have some *.conf.in files in system/local. Do they somehow magically override existing *.conf?

No, those are templates which are rewritten by the `entrypoint.sh` script.  You can see some the code in question here:

https://github.com/dmuth/splunk-lab/blob/434a53e500f520b804fd2718a1f10c045738ded3/entrypoint.sh#L84

As a user, you don't have to pay any attention to them, they're part of the tooling for the Docker image itself.

-- Doug

**Comment by kundeng** [comment]
when containers are stopped but not removed, they generally do retain states.  The issue is your entrypoint.sh is rerun upon restarting a container, and it probably overwrites any changes made to some files including web.conf.  

Anyway, decided to go with the stock splunk image and docker-compose.
